name: github-pages-docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment and Run Sphinx-build
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-1'
          environment-file: docs/environment.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
        run: |
          micromamba run -n eodms-api-client-rtd sphinx-build docs docs/_build       
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'          
          force_orphan: true